# SITE CONFIGURATION
title: Abhijit Balaji # your site title
author: Abhijit Balaji # You :P
description: > # Meta description of Homepage
  learning to learn!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abhijit-2592.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Abhijit Balaji
  links:
    - https://www.linkedin.com/in/abhijit-balaji
    - https://github.com/Abhijit-2592

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'CV', link: 'https://drive.google.com/file/d/1a2C-lCFUj1KCkfk_h6Dq4jSS_LuL_yi4/view?usp=sharing'}

tagline: >
    Learning To Learn!

hero_img: posts/deep_learning.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: abhijitbalaji1995@gmail.com # email for form submission

twitter_username: balaji_abhijit
github_username: Abhijit-2592 # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: abhijitblog # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
